# Generated by Django 3.2.6 on 2021-08-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, max_length=120, null=True, upload_to='')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('category', models.CharField(blank=True, max_length=120, null=True)),
                ('number_of_votes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Nominees',
            },
        ),
        migrations.AlterField(
            model_name='nominees',
            name='image',
            field=models.ImageField(blank=True, max_length=120, null=True, upload_to=''),
        ),
    ]
