# Generated by Django 3.2.6 on 2021-08-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominees', '0002_auto_20210822_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voteresults',
            options={'verbose_name_plural': 'Votting Results'},
        ),
        migrations.AddField(
            model_name='nominees',
            name='number_of_votes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
