# Generated by Django 3.2.6 on 2021-08-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominees', '0004_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominees',
            name='fullname',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
