# Generated by Django 3.2.6 on 2021-08-25 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nominees', '0006_nominees_is_image_compressed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominees',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nominees.categories'),
        ),
    ]
