# Generated by Django 3.2.6 on 2021-08-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominees', '0008_alter_nominees_number_of_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_image_compressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voteresults',
            name='is_image_compressed',
            field=models.BooleanField(default=False),
        ),
    ]
