# Generated by Django 3.2.6 on 2021-08-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominees', '0009_auto_20210826_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominees',
            name='Author',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
