# Generated by Django 3.2.6 on 2021-08-26 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominees', '0011_alter_nominees_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nominees',
            old_name='Author',
            new_name='author',
        ),
    ]
