# Generated by Django 3.2.6 on 2021-10-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominees', '0019_alter_director_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='index_arrange',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='nominees',
            name='index_arrange',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
