# Generated by Django 3.2.6 on 2021-08-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voter', '0003_alter_voters_generated_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voters',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
