# Generated by Django 3.2.6 on 2021-09-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voter', '0004_alter_voters_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='voters',
            name='voted_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
