# Generated by Django 3.2.6 on 2021-11-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voter', '0005_voters_voted_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voters',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='voters',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
    ]
